config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#latest'
  resources :articles do
    resources :comments
    resource :votes
  end
  resources :my_articles
  resources :high_views

  get 'homes/hot'
  get 'homes/oldest'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
  has_many :comments
  has_many :votes
  has_attached_file :image , styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  paginates_per 50
  def votes_count(value)
    votes.where(value: value).count
  end
  
  def increase_views_count
    Article.increment_counter(:views_count, self.id)
  end
  
  def self.hot_articles
    joins('LEFT JOIN votes ON votes.article_id = articles.id')
    .group('articles.id')
    .order('SUM(votes.value) DESC')
    
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  validates :content, presence: true
  has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments

  has_many :votes
  def vote!(article, value)
    vote = Vote.where(user: self, article: article).first_or_initialize
    vote.value = value
    vote.save!
  end

  def unvote!(article)
    Vote.where(user: self, article: article).delete_all
  end

  def voted?(article, value)
    Vote.where(user: self, article: article, value: value).exists?
  end

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :article_id, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  def check_user_signed_in
    if current_user == nil
      redirect_to new_user_session_path, alert: 'Phải đăng nhập trước'
    end
  end
  protected

 def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_user_signed_in, except: [:show]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article, notice: 'Đăng bài thành công'
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @article.increase_views_count
    @comment = Comment.new 
    
    @comments = @article.comments.order(created_at: :desc).page(params[:page])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: 'Sửa bài thành công'
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy

    redirect_to my_articles_path
  end

  def index
    @articles = Article.order(created_at: :desc).page(params[:page])
  end

  def article_params
    params.require(:article).permit(:title, :content, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_user_signed_in

  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(params.require(:comment).permit(:content))
    @comment.user = current_user
    @comment.article = @article

    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article), alert: 'Bình luận không hợp lệ'
    end
  end
end

app/controllers/concerns/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @article = Article.find(params[:article_id])
    @comment = Comment.new(params.require(:comment).permit(:content))
    @comment.user = current_user
    @comment.article = @article
    @comment = Comment.order('created_at DESC').limit(5)
    if @comment.save
      redirect_to article_path(@article) 
    else
      redirect_to article_path(@article), alert: 'Binh luan khong hop le'

    end

  end
end

app/controllers/high_views_controller.rb
class HighViewsController < ApplicationController
 

  def index
    @articles = Article.order('views_count DESC')
    
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def latest
    @articles = Article.order('created_at DESC').page(params[:page])
  end

  def hot
  	@articles = Article.hot_articles.order('SUM(votes.value) DESC').page(params[:page])
  end

  def oldest
    @articles = Article.order('created_at ASC').page(params[:page])
    
  end
end

app/controllers/my_articles_controller.rb
class MyArticlesController < ApplicationController
  before_action :check_user_signed_in

  def index
    @articles = current_user.articles.page(params[:page])
    
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :check_user_signed_in
  def create
    article = Article.find(params[:article_id])
    @vote = Vote.where(user_id: current_user.id, article_id: article.id).first
    if @vote == nil
      @vote = Vote.new(params.require(:vote).permit(:value))
      @vote.user = current_user
      @vote.article = article
      @vote.save!
    end
    redirect_to article_path(article)
  end
  def update
    article = Article.find(params[:article_id])
    value = params.require(:vote).require(:value)

    current_user.vote!(article, value)

    redirect_to article
  end

  def destroy
    article = Article.find(params[:article_id])
    current_user.unvote!(article)

    redirect_to article
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: {multipart: true } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group has-warning">
  <label class="control-label" for="inputWarning1">Tiêu đề</label>
  <span id="helpBlock2" class="help-block"><%= f.text_field :title %></span>
  
  </div>
  <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image%>
    </div> 
  <div class="form-group has-warning">
  <label class="control-label" for="inputWarning1">Nội dung</label>
  <span id="helpBlock2" class="help-block"=><%= f.text_area :content ,size: "60x12"%></span>

  
  </div>
  
  <div class="actions">
    <%= f.submit 'Đăng bài', data: {cofirm: "are you sure ?"}%>
  </div>
<% end %>

app/views/articles/_vote_button.html.erb
	<% if current_user.voted?(article, value) %>
	  <%= link_to article_votes_path(article), method: :delete, class:"btn active btn-default btn-lg" do %>
	    <span class="glyphicon glyphicon-thumbs-<%= value == 1 ? 'up' : 'down' %>"></span>
	    <%= article.votes_count(value) %>
	  <% end %>
	<% else %>
	  <%= link_to article_votes_path(article, vote: {value: value}), method: :put, class:"btn btn-default btn-lg" do %>
	    <span class="glyphicon glyphicon-thumbs-<%= value == 1 ? 'up' : 'down' %>"></span>
	    <%= article.votes_count(value) %>
	  <% end %>
	<% end %>
	

app/views/articles/_vote_buttons.html.erb
<% if user_signed_in? %>
	<div class="btn-group">
	  <%= render 'articles/vote_button', article: article, value: 1 %>
	  <%= render 'articles/vote_button', article: article, value: -1 %>
	</div>
<% else %>
	<p class="btn btn-warning"><%= link_to "Để bình chọn vui lòng đăng nhập ", new_user_session_path %></p>
<% end %>

app/views/articles/edit.html.erb
<h2>Sửa bài <%= @article.title %></h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<% if user_signed_in? %> 
  <% @articles.each do |f| %>
    <div class="form-group has-success">
      <label class="control-label col-sm-3" for="inputSuccess3">
        <%=truncate(f.title, length: 20)%>
      </label>
      <%= image_tag f.image.url(:thumb)%>
      <span id="helpBlock" class="help-block">
        <%= truncate(f.content, length: 140)%>
      </span><br/>
       
        
      Đăng bởi <%= f.user.email %>, Cách đây <%= time_ago_in_words(f.created_at) %>
      <%= link_to "show",article_path(f)%>
      <% if current_user.id == f.user.id %>
        <%= link_to 'Edit', edit_article_path(f) %>
      <% end %><br/><br/>
    </div>
  <% end %>
<% else %>
  <% @articles.each do |f| %>
    <div class="form-group has-success">
    <label class="control-label col-sm-3" for="inputSuccess3">
        <%=truncate(f.title, length: 20)%>
      </label>

    <span id="helpBlock" class="help-block">
      <%= image_tag f.image.url(:thumb)%>
      <%= truncate(f.content, length: 140)%>
    </span><br/>
    Đăng bởi <%= f.user.email %>, Cách đây <%= time_ago_in_words(f.created_at) %>
    <%= link_to "show",article_path(f)%>
    <br/><br/>
  </div>
  <% end %>
<% end %>
<%= paginate @articles %>

app/views/articles/new.html.erb
  <button type="button" class="btn btn-primary">New Post</button>
  <%= form_for @article, html: {multipart: true } do |f| %>
    <label class="control-label" for="inputWarning1">Title</label><br/>
    <%= f.text_field :title %><br/>
    <% if @article.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@article.errors[:title].count, 'error')%></h2>
      <% @article.errors[:title].each do |a| %>
          <%= a %>
      <% end %>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image%>
    </div>  
    <label class="control-label" for="inputWarning1">Content</label><br/>
    <%= f.text_area :content,size: "60x12" %><br/>
    <% if @article.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@article.errors[:content].count, 'error')%></h2>
      <% @article.errors[:content].each do |a| %>
          <%= a %>
      <% end %>
      </div>
    <% end %>
    
    <%= f.submit "create" %>
  <% end %>

app/views/articles/show.html.erb
<h2 class="list-group-item list-group-item-info">
  <%= @article.title %>
</h2>
<div class="article-content">
	<p class="panel panel-info">
	<%= image_tag @article.image.url(:large) %><br/>
  <%=@article.content %>
  <%= render 'articles/vote_buttons', article: @article %>
    
  </p>
</div>
<div class="article-footer">
	Đăng bởi <%= @article.user.email %>, Cách đây <%= time_ago_in_words(@article.created_at) %>
	<% if user_signed_in? && current_user == @article.user %>
		<%= link_to 'Edit', edit_article_path(@article),class: 'btn btn-warning btn-sm'%>
		<%= link_to 'Xoá', article_path(@article), method: :delete, data: { confirm: 'Bạn có muốn xoá bài này không?' },class: 'btn btn-danger btn-sm' %>
	<% end %>
</div>
<% if user_signed_in? %>
	<div class="comment-form">
		<%= form_for [@article, @comment] do |f| %>
			<%= f.text_area :content, placeholder: 'Bình luận của bạn', size:'72.5x2' %>
	
			<%= f.submit 'Lưu' %>
		<% end %>

	</div>
<% else %>
	<p class="btn btn-danger"><%= link_to "Hãy đăng nhập để bình luận", new_user_session_path %></p>
<% end %>
<br/>
<div class="comments">
	<p class="label label-default">Có <%= @comments.count %> bình luận:</p>
	<% @comments.each do |comment| %>
		<div class="comment">
			<div class"comment-content">
				<h2><span class="label label-primary"><%=comment.content %></span></h2>
			</div>
			<div class="comment-info">
				Bởi <%= comment.user.email %>, cách đây <%= time_ago_in_words(comment.created_at) %>
			</div>
		</div>
	<% end %>
</div>

app/views/high_views/index.html.erb
<% @articles.each do |f| %>
    <div class="form-group has-success">
      <span class="title">
        <%= link_to truncate(f.title, length: 20), article_path(f)%>
      </span>
      <div>
      <%= image_tag f.image.url(:large)%>
      </div>
      <span id="helpBlock" class="help-block">
        <%= truncate(f.content, length: 300)%>
      </span><br/>
       
      <div class="article-stats">
        <span class="glyphicon glyphicon-eye-open"></span> 
        <%= f.views_count%> lượt
        <%= render 'articles/vote_buttons', article: f %>
      </div>
      <br>
      Đăng bởi <%= f.user.email %>, Cách đây <%= time_ago_in_words(f.created_at) %>
      <%= link_to "show",article_path(f)%>
      <% if user_signed_in? %> 
        <% if current_user.id == f.user.id %>
          <%= link_to 'Edit', edit_article_path(f) %>
        <% end %><br/><br/>
      <% end %>
    </div>
  <% end %>

app/views/homes/_form.html.erb
<% if user_signed_in? %> 
  <% @articles.each do |f| %>
    <div class="form-group has-success">
      <span class="title">
        <%= link_to truncate(f.title, length: 20), article_path(f)%>
      </span>
      <div>
      <%= image_tag f.image.url(:large)%>
      </div>
      <span id="helpBlock" class="help-block">
        <%= truncate(f.content, length: 300)%>
      </span><br/>
       
      <div class="article-stats">
        <span class="glyphicon glyphicon-eye-open"></span> 
        <%= f.views_count%> lượt
        <span class="glyphicon glyphicon-comment"></span>
        <%= f.comments.count %> bình luận
        <%= render 'articles/vote_buttons', article: f %>
      </div>
      <br>
      Đăng bởi <%= f.user.email %>, Cách đây <%= time_ago_in_words(f.created_at) %>
      <%= link_to "show",article_path(f)%>
      <% if current_user.id == f.user.id %>
        <%= link_to 'Edit', edit_article_path(f) %>
      <% end %><br/><br/>
    </div>
  <% end %>
<% else %>
  <% @articles.each do |f| %>
    <div class="form-group has-success">
    <span class="title">
        <%= link_to truncate(f.title, length: 20), article_path(f)%>
      </span>
      <div>
      <%= image_tag f.image.url(:large)%>
      </div>
      <span id="helpBlock" class="help-block">
        <%= truncate(f.content, length: 300)%>
      </span><br/>
       
      <div class="article-stats">
        <span class="glyphicon glyphicon-eye-open"></span> 
        <%= f.views_count%> lượt<br>
        <span class="glyphicon glyphicon-comment"></span>
        <%= f.comments.count %> bình luận
        <%= render 'articles/vote_buttons', article: f %>
      </div><br/>
    Đăng bởi <%= f.user.email %>, Cách đây <%= time_ago_in_words(f.created_at) %>
    <%= link_to "show",article_path(f)%>
    <br/><br/>
  </div>
  <% end %>
<% end %>

<%= paginate @articles %>

app/views/homes/hot.html.erb
<h1>Homes#hot</h1>
<p>Find me in app/views/homes/hot.html.erb</p>

app/views/homes/latest.html.erb
<%= render 'homes/form' %>

app/views/homes/oldest.html.erb
<%= render 'homes/form' %>

app/views/layouts/_footer.html.erb
<div class="container">
  <hr/>
  <footer>
    <p>&copy; 2016 Company, Inc.</p>
  </footer>
</div> <!-- /container -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#main-menu">
        <span class="sr-only">Toggle navigationb</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar">
        </span>
      </button>
        <%= link_to image_tag("logo-large.png", width: '100', height: '50'), root_path ,{ class: "navbar-brand"}%>
    </div>
    <div class="collapse navbar-collapse" id="mai n-menu">
        <ul  class="nav navbar-nav">
        <li><%= link_to root_path do %>
              Recently
            <% end %>
        </li>
        <li><%= link_to homes_oldest_path do %>
              Oldest
            <% end %>
        </li>
        <li><%= link_to high_views_path do %>
              High Views
            <% end %>
        </li>
        <li><%= link_to homes_hot_path do %>
              High Votes
            <% end %>
        </li>
        
        
        <li><%= link_to 'Your Post',my_articles_path %></li>
        </ul>
    <ul class="nav navbar-nav navbar-right">
      
      <%if user_signed_in?%>
      <%= link_to image_tag(current_user.avatar.url(:thumb), class:"round-image-50"), edit_user_registration_path %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %><span class="caret"></span>
          </a>
        <ul class="dropdown-menu">
          <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span> Cập nhật thông tin cá nhân
          <% end %>
          </li>
          <li>
            <%= link_to new_article_path do %>
              <span class="glyphicon glyphicon-pencil"></span> Đăng bài
            <% end %>
          </li>
          <li>
            <%= link_to my_articles_path do %>
              <span class="glyphicon glyphicon-th-list"></span> Quản lý bài viết
            <% end %>
          </li>
          <li role="separator" class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Đăng xuất
            <% end %>
          </li>
        </ul>
        </li>
      <%else%>
        <div class="btn navbar-btn navbar-right">
          <%=link_to 'Đăng Ký', new_user_registration_path, class: "btn btn-default btn-sm"%>
          <%=link_to 'Đăng Nhập', new_user_session_path, class: "btn btn-success btn-sm"%>
        </div>
      <%end%>
    </ul>
    
       
    </div>
</nav>
      
      
    
    

app/views/layouts/_left.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <% @articles.hot_articles.each_with_index do |f, i| %>
    <li data-target="#myCarousel" data-slide-to="<%=i+1%>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active" style="width: 100%;height: 300px">
      <%= image_tag @articles.first.image.url(:large), class:'image'%>
      <div class="carousel-caption">
        <h3><%= @articles.first.title %></h3>
      </div>
    </div>    
    <% @articles.hot_articles.each do |f| %>
      <div class="item" style="width: 200;height: 300px">
        <%= image_tag f.image.url(:large), class:'image' %>
        <div class="carousel-caption">
          <h3><%= f.title %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    

    <title>Haivl</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </head>

  <body>


    <%= render 'layouts/header' %><br/><br/><br/><br/>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div >
      <div class="row">
        <div class="col-sm-2 col-sm-offset-1 blog-sidebar" style="margin-left: 100px">
          <div class="sidebar-module">
            <h4 class="category">Propose</h4>
            <ol class="list-unstyled">
              <%= render 'layouts/left'%>
              </ol>
          </div>
        </div>
        <div class="col-sm-6 blog-main" style="background-color: #D6FFFF">
          <div class="main">
            <div class="container" style="width: 100%">
              <div>
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              </div>
              <%= yield %>
            </div>
          </div>
        </div>
        <div class="col-sm-2 col-sm-offset-1 blog-sidebar" style="margin-right: 65px; margin-left: 10px">
          <div class="sidebar-module sidebar-module-inset">
            <h4 class="category">About</h4>
            <p>Haivl <em>(thường phát âm là: hài vê-lờ hoặc hài vờ-lờ )</em> là một trong những trang mạng xã hội giải trí phổ biến tại Việt Nam.</p>
          </div>
          <div class="sidebar-module">
            <h4 class="category">Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4 class="category">Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
    <%= render 'layouts/footer' %>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/my_articles/index.html.erb
<h2>Quản lý bài viết</h2>
<table class="table table-striped">
  <thead>
    <th>ID</th>
    <th>Tiêu đề</th>
    <td></th>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td>
          <%= link_to 'Xem', article_path(article), class: 'btn btn-default btn-sm' %>
          <%= link_to 'Sửa', edit_article_path(article), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Xoá', article_path(article), method: :delete, data: { confirm: 'Bạn có muốn xoá bài này không?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @articles %>